services:
  # dev:
  #   build:
  #     context: .
  #     dockerfile: ./notebooks/Dockerfile.dev

  #   depends_on:
  #     - mlflow

  #   command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''"]

  #   ports:
  #     - "8888:8888"

  #   volumes:
  #     - ./src/config/:/e2e_ml/src/config/
  #     - ./models:/e2e_ml/models/
  #     - ./data:/e2e_ml/data/

  # mlflow:
  #   build:
  #     context: .
  #     dockerfile: ./notebooks/Dockerfile.dev
  #   command: ["mlflow", "server", "-h", "0.0.0.0", "-p", "5000"]

  #   ports:
  #     - "5000:5000"

  #   volumes:
  #     - ./src/config/:/e2e_ml/src/config/
  #     - ./models:/e2e_ml/models/
  #     - ./data:/e2e_ml/data/

  prod:
    image: thong038202008963/repo:latest
    
    command: ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]

    ports:
      - "8000:8000"

    volumes:
      - ./models:/e2e_ml/models/
      - ./data:/e2e_ml/data/
      - ./reports:/e2e_ml/reports/
