[project]
name = "e2e-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "awscli>=1.42.45",
    "boto3>=1.40.45",
    "catboost>=1.2.8",
    "evidently>=0.7.15",
    "kaggle>=1.7.4.5",
    "lightgbm>=4.6.0",
    "loguru>=0.7.3",
    "mlflow>=3.4.0",
    "numpy>=2.2.6",
    "optuna>=4.5.0",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
    "xgboost>=3.0.5",
]
