FEATURES: ['Gender_Male', 'Age_q3', 'Age_q4', 'FAVC_yes', 'CALC_Sometimes', 'CALC_no', 'Weight', 'FCVC', 'NCP', 'FAF', 'TUE', 'BMI']
MODEL_NAME: 'lightbgm_cls'
MODEL_FLAVOR: 'lightgbm'
RUN_ID: '3faa3a1014f046e2986e818ad12d7a1b'
EXPERIMENT_ID: '2'
VERSION: '2'