name: Deploy Model to Staging

on:  
  pull_request:
    types: [closed]
  workflow_dispatch:                # Enables manual trigger
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Check out source code
        uses: actions/checkout@v5.0.0
        
      - name: Create credentials.yaml from secrets
        run: |
          mkdir -p src/config
          cat > src/config/credentials.yaml <<EOF
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          POSTGRESQL: ${{ secrets.POSTGRESQL }}
          S3: ${{ secrets.S3 }}
          EC2_URL: ${{ secrets.EC2_URL }}
          EOF
      
      # # Deploy model to a shadow/canary endpoint  
      # - name: Deploy Qwak Build
      #   uses: qwak-ai/deploy-action@v1
      #   with:
      #     qwak-api-key: ${{ secrets.QWAK_API_KEY }}
      #     deploy-type: 'realtime'                # Deploying a real time endpoint
      #     model-id: ${{ vars.QWAK_MODEL_ID }}    # Qwak Model ID
      #     build-id: ${{ github.head_ref }}       # Using the branch name as build ID
      #     param-list: |                                    
      #       variation-name=shadow,from-file=.config/deploy_conf.yaml
